DROP SCHEMA SENG_BYTES;
CREATE SCHEMA SENG_BYTES;
USE SENG_BYTES;

CREATE TABLE Editor (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	tipo INT NOT NULL DEFAULT 0,
	fecha_de_miembro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);

CREATE TABLE Suscriptor (
	id INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
	apellido VARCHAR(100) NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Suscripcion (
	id INT NOT NULL AUTO_INCREMENT,
	id_suscriptor INT NOT NULL,
	costo FLOAT NOT NULL,
	duracion INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(id_suscriptor) REFERENCES Suscriptor(id)
);

CREATE TABLE Articulo (
	id INT NOT NULL AUTO_INCREMENT,
	id_Revista INT,
	texto VARCHAR(3000),
	fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);

CREATE TABLE Autores_Articulos (
	id_Articulo INT NOT NULL,
	id_Autor INT NOT NULL,
	PRIMARY KEY(id_Articulo, id_Editor),
	FOREIGN KEY(id_Articulo) REFERENCES Articulo(id),
	FOREIGN KEY(id_Editor) REFERENCES Editor(id)
);

CREATE TABLE Revista (
	id INT NOT NULL AUTO_INCREMENT,
	mes INT NOT NULL,
	anio INT NOT NULL,
	PRIMARY KEY(id)
);